services:
  app:
    build:
      args:
        user: ${UNIX_USER}
        uid: ${UNIX_UID}
      context: ./
      dockerfile: Dockerfile
    image: siop
    container_name: siop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - siop

  nginx:
    image: nginx:alpine
    container_name: siop-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - siop

networks:
  siop:
    driver: bridge
